import { createHash } from "node:crypto";
import { env, MAX_NAME_LENGTH } from "./_env";

export const json = (body: unknown, status = 200): Response =>
  new Response(JSON.stringify(body), {
    status,
    headers: { "content-type": "application/json", "cache-control": "no-store" },
  });

export const fail = (status: number, error: string): Response => json({ error }, status);

/** Netlify's real client IP, ahead of the CDN hop. */
export const clientIp = (req: Request): string | null =>
  req.headers.get("x-nf-client-connection-ip") ??
  req.headers.get("x-forwarded-for")?.split(",")[0]?.trim() ??
  null;

const sha256 = (value: string): string => createHash("sha256").update(value).digest("hex");

/** Addresses are only ever stored hashed, for rate limiting. */
export const hashIp = (ip: string | null): string | null =>
  ip ? sha256(`${ip}|${env("HASH_SALT")}`) : null;

/**
 * Run tokens and player ids are both uuids. A player id is generated by the
 * browser to group a person's runs; it is not an identity claim and nothing is
 * trusted to it.
 */
export const isUuid = (v: unknown): v is string =>
  typeof v === "string" &&
  /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(v);

/** Collapse whitespace, drop control characters, and cap the length. */
export function cleanName(raw: unknown): string | null {
  if (typeof raw !== "string") return null;
  const name = Array.from(raw)
    .filter((ch) => {
      const code = ch.codePointAt(0) ?? 0;
      return code >= 32 && code !== 127;
    })
    .join("")
    .replace(/\s+/g, " ")
    .trim();
  if (!name || name.length > MAX_NAME_LENGTH) return null;
  return name;
}
